name: Build Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.17.x'

      - name: Get node version
        id: node-version
        run: |
          echo "::set-output name=ver::$(node --version)"
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.node-version.outputs.ver }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache install
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-dep-${{ steps.node-version.outputs.ver }}-${{ hashFiles('**/package-lock.json') }}

      - run: npm install

      - name: Install sharp and modify config
        run: |
          npm i gatsby-plugin-sharp gatsby-transformer-sharp
          sed -i 's/\/\/ INSERT SHARP HERE/"gatsby-plugin-sharp",\n    "gatsby-transformer-sharp",/g' gatsby-config.js

      - run: npm run build
